--- 
title: "Master Thesis: The (hidden) Benefits of Monitoring"
author: "Hauke C. Roggenkamp"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
always_allow_html: yes
bibliography: [references.bib]
biblio-style: apalike
link-citations: yes
---

# Introduction {#Intro}

> There seems to be a common wisdom that monitoring affects the workers' output negatively. A popular rationale is that it signals distrust and triggers psychological costs which are reciprocally passed back to the managers. As a consequence, the managers risk to suffer losses if they increase the level of attention they pay  to their workers. These detrimental effects can be labeled as the hidden costs of monitoring and are subject to a rich body of empirical and theoretical work. Most of these studies identify monitoring as a management practice that is perceived as unkind in some sense and design or model it as such. 
Because we believe that monitoring is neither a bad nor a good management practice _per se_, we suggest a more nuanced contemplation. To this end we designed a laboratory experiment where monitoring can be perceived as kind or unkind. We hypothesize that workers reciprocate this perceived (un)kindness via their labor supply. Whether a worker perceives monitoring as kind or unkind is expected to depend on her productivity: Productive workers benefit from monitoring and perceive it as kind. Unproductive workers, in contrast, suffer from monitoring and perceive it as unkind. 
The underlying idea is easily understood in real-world applications such as in human resource managers' decisions that concern wage re-negotiations or promotions, for example.  In such scenarios, monitoring is likely to help the manager to make informed decisions on the basis of relevant metrics (such as a worker's productivity). If the manager lacks assessments of the worker's productivity,  she has to rely on inferior, if not arbitrary, characteristics that are easily observable, such as a worker's tenure. A young, ambitious and talented worker will likely benefit from monitoring as it implies that the manger's decision is based on work samples. Slow-going workers who already spent some years in the company would, in contrast, prefer the promotion decision to be based on the tenure.  After all, that measure is unrelated to their work and improves their chances to be promoted. 
We expect the unproductive workers to express their discomfort of being monitored while the productive workers express their gratitude. We designed a laboratory experiment where the workers' labor supply is the only channel to express these emotions. Applying an intention-based reciprocity model in this setup, I theoretically predict one and the same action (monitoring) to have unsuspected costs _and_ benefits.
The results demonstrate that the workers' behavior cannot be explained by a standard model that assumes them to be purely self-interested. Using OLS regressions, OLS-based simulations, Fisher's exact test as well as a regression discontinuity design, I find mixed results whose sum I interpret as supporting evidence for the intention-based reciprocity predictions: The OLS's regression coefficients (that highly depend on three extreme values) are insignificant which indicates that there is no relationship between the workers' working morale, their productivity and monitoring; the simulations indicate that monitoring spoils the workers' working morale; Fisher's exact test finds that productive workers who were unobserved reduced their workload significantly more often than unproductive workers who were not observed while the opposite holds true for monitored workers; and the regression discontinuity design turns out to be impractical to analyze our data. Because the OLS' and OLS-based simulations' results are sensitive to only three observations and because the workload (analyzed with Fisher's exact test) is a good predictor of the workers' initial intention to work, I interpret the sum of the results as follows: Workers, who were unproductive and disliked to be monitored, punished the monitoring manager by working less. Simultaneously, productive workers who were monitored suffered less and therefore lowered their effort provision by less than their unproductive colleagues. 
Importantly, we do not find any hidden benefits of monitoring, that is, workers, who perceive the managers' intentions to monitor them to be kind, do not work harder than they would if they had no emotions. It simply appears as if this group of workers either perceived the managers' intentions as neutral or as if they had no channel to express kindness in practice: I suspect that we would have found hidden benefits if it was easier for workers to work more or better. I therefore suggest to adjust the experimental design accordingly.
Regardless of whether monitoring triggers hidden benefits or whether the hidden costs disappear, this thesis suggests that the application of monitoring as a management practice needs to be assessed in a more nuanced way than the current literature suggests. The workers productivity appears to be a good candidate to unravel these nuances. The _empathetic_ monitoring of workers might then explain parts of the persistent performance differences across seemingly similar firms.

How does monitoring affect the agents' working morale? There is a wide-spread belief that monitoring spoils the working morale and therefore, comes at hidden costs.  It might, for instance,  be perceived as a lack of trust and trigger psychological costs. These psychological costs are then reciprocally passed back to the agent through a decreased effort provision [@Dickinson2008]. Experiments (such as Falk's and Kosfeld's [@FalkKosfeld]) that support this claim are often designed in a way that the data could not possibly support other conclusions.^[See [@SiemensJEBO2013; @Legitimacy; @GroupIdentity] for further references that analyzed their experimental design.] While Falk and Kosfeld designed an experiment in which the principals restrict the agents' autonomy, there also is a growing number of studies that model several other control devices, namely "managerial attention", "supervision", "verification" or "monitoring" [@Schulze2003; @Guerra; @Dickinson2008]. Their experimental setup is similar to the one of Falk and Kosfeld as they allow the application of these devices to only be perceived as a breach of trust.

While we acknowledge that all these management practices (to which I henceforth refer as "monitoring") may have detrimental effects on the agents' working morale, we also believe that they might be perceived as fair so that could also motivate the agent intrinsically. We argue that monitoring helps to receive high quality signals of the agent's performance and therefore minimizes the problem of incorrectly receiving bad performance signals. Monitoring can thus also be seen as a good management practice [@HalacPrat] that helps to make legitimate decisions relating to the assignment of prestigious projects, salary negotiations, promotions \emph{et cetera}.  Furthermore, employees might be more motivated if they know that these decisions are made on the basis of a valid performance assessment instead of arbitrary characteristics such as the employee's tenure [@BloomQJE2007, pp.1356].  In our view, the belief that monitoring, if anything, spoils the working morale is too narrowly considered since it does not cover this positive dimension sufficiently. That is not to say that we believe monitoring to have positive effects \emph{per se}. Instead, we argue that the circumstances determine whether monitoring is perceived as kind or unkind. To study a more nuanced view, we designed a laboratory experiment that allows for both (kind and unkind) perceptions. While this enables us to investigate hidden costs in form of a low level of effort provision (due to perceived unkindness that is reciprocally passed back to the principal) the design also allows us to search for hidden \emph{benefits} of monitoring -- at least to some extend.

The idea that the same action is perceived as legitimate in some scenarios while it is perceived as unjust in others is not new. A price increase, for instance, seems to be only perceived as unkind if the producer's costs did not increase [@Okun]. Similarly, it is perceived as unjust to cut wages if the employer's wellbeing is not at stake. If it was at risk however, employees might accept it [@Kahneman]. Finally, and more related to this thesis, the employer's control seems to crowd-out the employees intrinsic motivation to supply labor if it is not legitimate, that is, if it does not prevent antisocial behavior [@Legitimacy]. The restriction of internet or social media access in a small sized family business may be perceived as unjust as it signals distrust. The same policy might, however, be perceived as neutral in the setting of a large multi-national firm, where the inter-personal ties are weaker and the risk of selfish behavior is higher. Similarly [@Barkema] and [@Frey1993] find suggesting evidence that the monitoring of hours worked can crowd-out the workers' motivation (and performance) if the monitoring principal was their own CEO while it has positive effects on their performance if the principal was a distant parent company. These studies, amongst others, suggest that one and the same action can be moderated by another variable that determines how this particular action is perceived.  In our experiment, we identify the agent's productivity as such a variable.


To put it in a nutshell, our intention was to create situations in which overachievers, in contrast to layabouts, appreciate to be monitored and reciprocate this sense of appreciation. We therefore analyze the effect of the interaction of monitoring and the agents' productivity on the agent's working morale. To do so, we implemented an experimental principal-agent game in which the agent supplied labor in a real-effort task. This was costly for her but generated profit for the principal. Importantly, the principal, who paid the agent's salary was not able to directly observe the agent's output. Instead, the principal chose one out of two available mechanisms that we interpret as attention technology and thus, as monitoring. The chosen mechanism generated the agent's salary. Under both mechanisms, the agent's salary consisted of a flat wage and the chance to also receive a bonus payment. While the random mechanism flipped a virtual coin to determine whether the agent receives the bonus, the performance-based mechanism was more likely to pay out the bonus the higher the agent's performance was.  Choosing the performance-based mechanism was, in a metaphorical sense, like observing the movements of the agent to make the bonus decision -- the better her performance, the better the principal's impression of her work, the likelier it becomes that she receives the bonus if she worked well. The choice of the random mechanism is, in contrast, interpreted as a complete lack of monitoring: the principal had no impression of her work such that the agent's earnings must be determined randomly. The random mechanism therefore sent completely arbitrary performance signals that determined the agent's earnings and were likely to be incorrect. Monitoring consequently was valuable to the principal as it incentivized the agent to exert effort. In addition, it was beneficial for agents, who expected to perform well because it yielded better chances to earn the bonus than the coin flip. In contrast, it was disadvantageous for layabouts, who could hope for a lucky outcome of the the random mechanism's coin flip.

An important feature of our design is that both the principal and the agent received an objective assessment of the agent's \emph{productivity} (or "talent") before the principal decided whether to monitor the agent. This assessment was based on the exact same task, which the two players executed in a previous stage of the experiment. In addition, both mechanisms avoided ex post hold-up problems because they were a function of a performance signal. A principal could thus, only decide on the signal's quality but not on the eventual payment she had to offer the agent. Consequently, we modeled a situation of complete contracts. Another important feature was that the agent learned the principal's choice of the mechanism before she worked for the principal, that is, whether the principal paid attention or not. We exploit these two features to analyze whether an agent provided more effort than her productivity would suggest if the principal chose the mechanism that was beneficial to the agent. In addition, we are interested in the agents' behavior if the principal chose the mechanism that was disadvantageous to them. In the latter case, we hypothesized them to provide less effort than one would expect (given their productivity). If this was the case, the "wrong" monitoring decision would have detrimental effects on the agent's working morale -- \emph{hidden costs}. In contrast, the "right" choice would yield \emph{hidden benefits}. The rational principal might then have an incentive not to pay attention to the agent's work, that is, to choose the random mechanism, albeit provoking a moral hazard.


The results are mixed. They do not support the hypothesis that agents react kindly to monitoring.[^This might, however, be due to the experimental design: While it was easy to exert low levels of effort, it was hard to go beyond one's boundaries which were set by the individual productivity.] We therefore find no evidence for hidden benefits of monitoring. The hidden costs of monitoring, however, are present in our data. We find that the average unproductive agent decreases her effort provision by about three to twelve percentage points, if monitored. Although it should not be interpreted as a causal effect of monitoring, the data also show that principals who monitored the agents realized higher payoffs. The discrepancy between hidden costs on the one hand and higher payoffs on the other hand cannot be explained by higher performances. Instead, it might be a result of chance (despite the significant p-value). Furthermore, and as predicted, the data also suggest that these hidden costs disappear for productive agents who benefit from monitoring. The latter observation, however, depends on the subset of data and methods applied. After all, the fraction of productive agents, who refused to supply effort while being monitored is relatively low. The unfirm robustness of the results calls for a continued data collection as well as an additional, refined treatment.

Investigating a more nuanced picture of the hidden effects of control helps to investigate management styles and their effect on the firms' productivities, profitabilities and survival rates [@BloomQJE2007]. [@gibbons2012, ch.~17] as well as [@BartelsmanDoms2000] and  [@Syverson] review a variety of studies and conclude that there are persistent performance differences across seemingly similar enterprises that may, in part, be explained by managerial skills and practices. Micromanagement might, for instance, have detrimental effects by eroding the workers' motivation [@Micromanagement]. We aim to identify monitoring as a management practice that affects the agent's working morale conditional on her characteristics. As such, we investigate whether monitoring is a  practice that (1) may explain some of the performance differences across firms and that (2) requires skilled managers who are able to identify who benefits or suffers from their attention.
